### ISSUE TITLE
Invisible Armor Option (request)

### ISSUE THREAD

**Issue by realhumii** [MattHeffNT/skin-packer#13]
Please can you add an option to the skin packer that makes your armor invisible to everyone? Thanks!

**Comment by MattHeffNT** [comment]
Hey thanks for raising an issue. Just so I understand. Do you want a Minecraft skin where you can see your character as normal and whenever you put on armour (regardless of type) the armour is invisible?

Thanks

**Comment by realhumii** [comment]
Yes, that's perfectly correct.

I've been trying to find out how on the internet for ages and I couldn't find anything so adding this option will help me a lot. Thanks!

(if it's patched, I can always downgrade)

**Comment by HumaanK** [comment]
yes please add invis armor

**Comment by MattHeffNT** [comment]
I think this would be an armour mod rather than a custom skin? which is a bit outside of the scope of this application.

**Comment by realhumii** [comment]
Really? I've seen multiple people use skin packs to hide their armor. And plus, there are no mods that hide armor for Bedrock Edition.

And also:

![image](https://user-images.githubusercontent.com/118684869/216771211-8b4788d6-7715-4358-ba53-ef51557fc4de.png)

**Comment by MattHeffNT** [comment]
> Really? I've seen multiple people use skin packs to hide their armor. And plus, there are no mods that hide armor for Bedrock Edition.
> 
> And also:
> 
> ![image](https://user-images.githubusercontent.com/118684869/216771211-8b4788d6-7715-4358-ba53-ef51557fc4de.png)

This is outside the scope of this web-app (unless anyone can link me specific skin packs that do this).
